### ISSUE TITLE
Name of properrty

### ISSUE THREAD

**Issue by scinfu** [sotnikov-link/getKey#1]
Can I access to name property of class or interface? 
like:

```
import { keyof } from "ts-keyof"
interface IModel {
  id: string
  name: string
}
console.log("Name of property",keyof(IModel.name)))
```

**Comment by sotnikov-link** [comment]
@scinfu

It's not possible, because IModel is TypeScript Interface. TypeScript Entities doesn't exist in runtime.

I can add `keyof<IModel>("name")` that will be give you "Name of property". Do you want it?

**Comment by scinfu** [comment]
@sotnikov-link  Yes, if the name "name" will wrong ES will detect the error?
es: `keyof<IModel>("namex")`

**Comment by sotnikov-link** [comment]
@scinfu if you use function below then TypeScript gives error for your case:

```typescript
function getKeyOf<T extends object>(keyName: keyof T) {
  return keyName;
}

interface IModel {
  id: string
  name: string
}

getKeyOf<IModel>("name") === "name" // 👍

getKeyOf<IModel>("wrongKey") // 👎  Argument of type '"wrongKey"' is not assignable to parameter of type 'keyof IModel'.(2345)
```

[TypeScript Play](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAcwKZQNKoJ4HlgA8AKoqgB5SpgAmAzonAEYBWq0AfABQDWOAcgEMAtqgBciXtjjBERAJSIA3gChEiAE7oQ6pJMEiA3MoC+y5TDCV1wARFSIAkgFk41VABslqxDGrjaUOoWyN5gwmKIAUFgIabKaJg4+ATOrh5cAERhIhkKALwFiFnhGYgA9GWIgLwbgLI7ZglYeISpbu6ZAO7qCMiNueWVVYByO4gAgurIICKWDDJQ2AAO9gDkGZ3dvUs+9GBwUIgCtLQwyGGM7vZQcIjzAurhVjOIc4uIS5LSji6tSwB0nABMAGYACwAVjkyiAA)

This function doesn't work for TypeScript Refactoring so I don't want add this function in package `ts-keyof`.

**Comment by scinfu** [comment]
@sotnikov-link nice.
Thank you
