### ISSUE TITLE
Not usable for passing the variable name to a (test data) function

### ISSUE THREAD

**Issue by rklec** [sotnikov-link/getKey#4]
![grafik](https://github.com/sotnikov-link/ts-keyof/assets/71322635/9fb0b94a-a637-49fd-9539-4bf4036422de)

> TS2448: Block-scoped variable  testData used before its declaration.

This is not possible for this code, as the variable is not defined yet. However, this was my use case and I thought this package would fix it:
```ts
const testData = getSomeTestData(keyof({ testData }));
```

The use case is to get a _named_ test data object (in whatever way) that has it's variable name embedded.

**Comment by sotnikov-link** [comment]
It's constrain of JavaScript.
ts-keyof doesn't use any magic.

Google Chrome / DevTools Console

<img width="439" alt="image" src="https://github.com/sotnikov-link/ts-keyof/assets/10273334/23dce5a3-6983-470e-ad7f-0172864f4274">

TypeScript Playground

<img width="578" alt="image" src="https://github.com/sotnikov-link/ts-keyof/assets/10273334/1f237ff1-e78f-45df-8152-01d830de0893">


https://www.typescriptlang.org/play?#code/MYewdgzgLgBAHjAvPGBqGBWA3AKB6SWAQyRgGUoAnASzAHMAKIgSlyA

You need to define variable before use.

```ts
let testData;
testData = getSomeTestData(keyof({ testData }));
```

https://www.typescriptlang.org/play?#code/DYUwLgBAhg3AUFCBeCBlMAnAlgOwOYAUUAlPEA
